name: Run Benchllama Benchmark

on:
  workflow_dispatch:
    inputs:
      model:
        description: 'Model to benchmark'
        required: true
        default: 'deepseek-r1:8b'
      samples:
        description: 'Number of samples'
        required: false
        default: '10'

env:
  GPU_TYPE: "NVIDIA RTX 2000 Ada Generation"
  IMAGE_NAME: "ollama/ollama"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install runpodctl
        run: wget -qO- cli.runpod.net | bash

      - name: Configure runpodctl
        run: runpodctl config --apiKey ${{ secrets.API_KEY }}

      - name: Create RunPod pod
        run: |
          CREATE_OUTPUT=$(runpodctl create pod --ports '11434/tcp' --secureCloud --gpuType "$GPU_TYPE" --imageName "$IMAGE_NAME")
          echo "$CREATE_OUTPUT"
          POD_ID=$(echo "$CREATE_OUTPUT" | awk -F'"' '/pod "/ {print $2}')
          echo "POD_ID=$POD_ID" >> $GITHUB_ENV

      - name: Get RunPod pod details
        run: |
          POD_DETAILS=$(runpodctl get pod $POD_ID -a)
          echo "$POD_DETAILS"
          ENDPOINT=$(echo "$POD_DETAILS" | awk -F'[: ]+' '/->11434/ {print $1 ":" $2}')
          echo "ENDPOINT=$ENDPOINT" >> $GITHUB_ENV

      - name: Wait for pod to be ready
        run: sleep 30

      - name: Pull model
        run: |
          curl -X POST "https://$ENDPOINT/api/pull" \
          -H "Content-Type: application/json" \
          -d '{ "model": "${{ inputs.model }}" }'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Benchllama
        run: pip install benchllama

      - name: Run Benchllama Benchmark
        run: |
          mkdir -p /tmp/benchllama
          benchllama evaluate \
            --models "${{ inputs.model }}" \
            --eval \
            --samples "${{ inputs.samples }}" \
            --provider-url "https://$ENDPOINT"

      - name: Archive benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchllama-results
          path: /tmp/benchllama
