name: Run Benchllama Benchmark

on:
  workflow_dispatch:
    inputs:
      model:
        description: 'Model to benchmark'
        required: true
        default: 'deepseek-r1:8b'
      samples:
        description: 'Number of samples'
        required: false
        default: '10'
      language:
        description: 'Benchmark language (python or js)'
        required: true
        default: 'python'        

env:
  GPU_TYPE: "NVIDIA RTX 2000 Ada Generation"
  IMAGE_NAME: "ollama/ollama"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install runpodctl
        run: wget -qO- cli.runpod.net | sudo bash

      - name: Configure runpodctl
        run: runpodctl config --apiKey ${{ secrets.API_KEY }} || ls ~/runners

      - name: Create RunPod pod
        run: |
          CREATE_OUTPUT=$(runpodctl create pod --ports '11434/tcp' --secureCloud --gpuType "$GPU_TYPE" --imageName "$IMAGE_NAME")
          POD_ID=$(echo "$CREATE_OUTPUT" | awk -F'"' '/pod "/ {print $2}')
          echo "POD_ID=$POD_ID" >> $GITHUB_ENV

      - name: Wait for pod to be ready
        run: sleep 60         

      - name: Get RunPod pod details
        run: |
          POD_DETAILS=$(runpodctl get pod $POD_ID -a)
          ENDPOINT=$(echo "$POD_DETAILS" | grep -oP '(?<=\s)\d+\.\d+\.\d+\.\d+:\d+(?=->11434)')
          echo "ENDPOINT=$ENDPOINT" >> $GITHUB_ENV

      - name: Pull model
        run: |
          curl -X POST "http://$ENDPOINT/api/pull" \
          -H "Content-Type: application/json" \
          -d '{ "model": "${{ inputs.model }}" }'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Benchllama
        run: pip install benchllama

      - name: Run Benchllama Benchmark
        run: |
          benchllama evaluate \
            --models "${{ inputs.model }}" \
            --eval \
            --samples "${{ inputs.samples }}" \
            --languages "${{ inputs.language }}" \
            --dataset "data/${{ inputs.language }}/humanevalpack.jsonl" \
            --provider-url "http://$ENDPOINT""

      - name: Archive benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchllama-results
          path: /tmp/benchllama
          
      - name: Remove RunPod pod
        if: always()
        run: runpodctl remove pod $POD_ID
